<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219174116 extends AbstractMigration
{

    public function getDescription(): string
    {
        return 'Create orders table with composite index';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, point_of_sale_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F52993986B7E9A73 ON "order" (point_of_sale_id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993986B7E9A73 FOREIGN KEY (point_of_sale_id) REFERENCES point_of_sale (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993986B7E9A73');
        $this->addSql('DROP TABLE "order"');
    }

}
